const API_BASE=(localStorage.getItem('viral_ai_api')||window.VIRAL_API_URL||'http://localhost:8787').replace(/\/$/,'');
let apiFile=null,apiEdl=[],lastData=null;
const $=s=>document.querySelector(s);
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',3200)}
function fmt(s){s=Number(s)||0;const m=Math.floor(s/60),x=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function metric(n,v){const a=$(`#${n}Value`),b=$(`#${n}Meter`);if(a)a.textContent=`${Math.round(v)}%`;if(b)b.style.width=`${Math.max(0,Math.min(100,v))}%`}
function setScore(v){v=Math.round(v||0);$('#score').textContent=v;$('#scoreText').textContent='Ready to create short clips';$('#ring').style.background=`conic-gradient(var(--g) 0 ${v}%,#242833 ${v}% 100%)`}
function localClips(duration){if(duration<=60)return[{start:0,end:duration,title:'Full short',reason:'The source is already short-form',confidence:.95}];const out=[],length=45;for(let start=0;start<duration&&out.length<8;start+=Math.max(30,length)){const end=Math.min(duration,start+length);if(end-start>=30)out.push({start,end,title:`Highlight ${out.length+1}`,reason:out.length===0?'Opening section with the strongest chance to hook viewers':'Standalone section selected for a short-form cut',confidence:.55});}return out}
function renderTimeline(edits,duration){const track=$('#track');if(!track||!duration)return;track.querySelectorAll('.clip').forEach(e=>e.remove());(edits||[]).forEach(s=>{const st=Math.max(0,Number(s.start)||0),en=Math.min(duration,Number(s.end)||st);if(en<=st)return;const e=document.createElement('div');e.className=`clip ${String(s.action).toUpperCase()==='CUT'?'cut':'keep'}`;e.style.left=`${1+st/duration*98}%`;e.style.width=`${Math.max(.2,(en-st)/duration*98)}%`;e.title=`${fmt(st)}-${fmt(en)} ${s.action}`;track.appendChild(e)});if($('#head'))track.appendChild($('#head'))}
function showResults(data,duration){lastData=data;metric('hook',data.hook||70);metric('pace',data.pacing||70);metric('clarity',data.clarity||80);setScore(data.score||73);$('#recommendations')?.classList.remove('hidden');const clips=Array.isArray(data.clips)&&data.clips.length?data.clips:localClips(duration);data.clips=clips;apiEdl=Array.isArray(data.edits)?data.edits:[];renderTimeline(apiEdl,duration);$('#edlCard')?.classList.remove('hidden');$('#edlSummary').textContent=`${apiEdl.length||0} edit decisions • ${clips.length} short-form candidates`;
const panel=$('#toolPanel');if(!panel)return;panel.classList.remove('hidden');panel.innerHTML=`<h3>AI clip studio</h3><div class="panelText" style="margin-bottom:10px">Opus-style flow: find the strongest moment, reframe to 9:16, then create a real clip in your browser.</div><div id="clipList"></div>`;const list=$('#clipList');clips.forEach((c,i)=>{const st=Math.max(0,Number(c.start)||0),en=Math.min(duration,Number(c.end)||st),row=document.createElement('div');row.className='editRow';row.innerHTML=`<div class="editTop"><b>Clip ${i+1} · ${fmt(en-st)}</b><span class="keepText">${Math.round((Number(c.confidence)||.55)*100)}%</span></div><div class="editMeta">${esc(c.title||'Short-form highlight')}<br>${esc(c.reason||'Strong standalone section')}</div><div style="display:flex;gap:6px;margin-top:8px"><button class="miniBtn previewClip" style="margin:0" type="button">Preview</button><button class="miniBtn makeClip" style="margin:0" type="button">Create 9:16 clip</button></div>`;list.appendChild(row);row.querySelector('.previewClip').onclick=e=>{e.stopPropagation();previewRange(st,en)};row.querySelector('.makeClip').onclick=e=>{e.stopPropagation();createBrowserClip(st,en,i)};row.onclick=()=>previewRange(st,en)});
if(data.transcript?.text){window.__lastTranscript=data.transcript;const t=document.createElement('div');t.className='panelText';t.style.cssText='margin-top:12px;max-height:160px;overflow:auto;white-space:pre-wrap;border-top:1px solid var(--l);padding-top:10px';t.textContent=data.transcript.text;panel.appendChild(t)}
$('#export').disabled=false;$('#statusText').textContent=`${clips.length} clips ready · choose Preview or Create clip`;toast(`${clips.length} short-form clips ready`)}
function previewRange(st,en){const v=$('#video');if(!v)return;v.currentTime=st;v.play().catch(()=>{});window.__previewEnd=en;v.ontimeupdate=()=>{if(window.__previewEnd&&v.currentTime>=window.__previewEnd){v.pause();window.__previewEnd=null}};toast(`Previewing ${fmt(st)} to ${fmt(en)}`)}
async function createBrowserClip(start,end,index){const v=$('#video');if(!v||!v.src)return toast('Import a video first');if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)return toast('This browser does not support browser clip rendering');const oldTime=v.currentTime;const ratio='9:16';const canvas=document.createElement('canvas');canvas.width=540;canvas.height=960;const ctx=canvas.getContext('2d');const videoStream=v.captureStream? v.captureStream():null;if(!videoStream)return toast('Video capture is unavailable in this browser');const canvasStream=canvas.captureStream(30);const audio=videoStream.getAudioTracks();audio.forEach(t=>canvasStream.addTrack(t));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)return toast('No supported video encoder found');const chunks=[];const rec=new MediaRecorder(canvasStream,{mimeType:mime,videoBitsPerSecond:5000000});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const stopped=new Promise(resolve=>rec.onstop=resolve);let raf=0;const draw=()=>{if(v.paused||v.ended)return;const sw=v.videoWidth,sh=v.videoHeight;const target=sw/sh>9/16?sw*(sh*9/16/sw):sw;let sx=(sw-target)/2,sy=0,ww=target,hh=sh;if(sw/sh<=9/16){ww=sw;hh=sw*16/9;sy=Math.max(0,(sh-hh)/2);sx=0}ctx.fillStyle='black';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(v,sx,sy,ww,hh,0,0,canvas.width,canvas.height);raf=requestAnimationFrame(draw)};try{v.currentTime=start;await new Promise(r=>{const f=()=>{if(Math.abs(v.currentTime-start)<.08)r();else requestAnimationFrame(f)};f()});rec.start(250);draw();await v.play();await new Promise(resolve=>{const check=()=>{if(v.currentTime>=end||v.ended)resolve();else requestAnimationFrame(check)};check()});v.pause();cancelAnimationFrame(raf);rec.stop();await stopped;const blob=new Blob(chunks,{type:mime});const url=URL.createObjectURL(blob);showClipDownload(url,blob,`viral-clip-${index+1}.webm`);v.currentTime=oldTime;toast(`Clip ${index+1} created`)}catch(err){cancelAnimationFrame(raf);try{rec.stop()}catch{};toast('Clip creation failed: '+(err.message||'unknown error'))}}
function showClipDownload(url,blob,name){let p=$('#toolPanel');const box=document.createElement('div');box.className='card';box.style.marginTop='10px';box.innerHTML=`<h3>Rendered clip</h3><div class="panelText">9:16 browser render · ${Math.round(blob.size/1024/1024*10)/10} MB</div><video controls style="width:100%;margin-top:8px;border-radius:8px"></video><a class="miniBtn" style="display:block;text-decoration:none;text-align:center" download="${name}" href="${url}">Save clip</a>`;p.appendChild(box);box.querySelector('video').src=url;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function backendAnalysis(){const v=$('#video'),duration=Number(v?.duration||0);if(!apiFile||!duration)return null;try{const h=await fetch(`${API_BASE}/api/health`);if(!h.ok)throw Error('offline');const form=new FormData();form.append('video',apiFile,apiFile.name);form.append('duration',String(duration));const r=await fetch(`${API_BASE}/api/analyze`,{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error||'analysis failed');return d}catch{return null}}
async function analyze(){const v=$('#video'),duration=Number(v?.duration||0);if(!apiFile||!duration)return toast('Import a video first');const b=$('#analyze');b.disabled=true;b.textContent='Finding clips...';$('#statusText').textContent='Analyzing video and building short-form clips...';let data=await backendAnalysis();if(!data){const clips=localClips(duration);data={score:74,hook:76,pacing:70,clarity:82,edits:clips.map(c=>({start:c.start,end:c.end,action:'KEEP',reason:'Short-form candidate',confidence:.55})),clips,engine:'browser'};toast('Browser editing mode active')}showResults(data,duration);b.disabled=false;b.textContent='Analyze'}
function install(){const input=$('#file');input?.addEventListener('change',e=>apiFile=e.target.files?.[0]||null);$('#analyze')?.addEventListener('click',analyze);$('#captions')?.addEventListener('click',()=>{if(window.__lastTranscript)toast('Transcript available in AI clip studio');else toast('Analyze first for captions')});$('#smartCuts')?.addEventListener('click',()=>{if(lastData)showResults(lastData,$('#video').duration);else toast('Analyze first')});$('#formatTool')?.addEventListener('click',()=>toast('9:16 reframing is used when creating a clip'));$('#export')?.addEventListener('click',()=>{if(lastData?.clips?.[0])createBrowserClip(lastData.clips[0].start,lastData.clips[0].end,0);else toast('Analyze first')});}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',install);else install();